In [1]:
import pandas as pd 
import json
df= pd.read_csv("dataset/spider_data/final_86_classes.csv")
df.describe()

        Unnamed: 0
count  7000.000000
mean   3499.500000
std    2020.870275
min       0.000000
25%    1749.750000
50%    3499.500000
75%    5249.250000
max    6999.000000

In [2]:
df.head()

,Unnamed: 0,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql
0,0,department,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ..."
1,1,department,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","List the name, born state and age of the heads...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ..."
2,2,department,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","List the creation year, name and budget of eac...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ..."
3,3,department,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What are the maximum and minimum budget of the...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ..."
4,4,department,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees of the...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ..."

In [3]:
a=df["db_id"].unique()
len(a)
a

array(['department', 'farm', 'student', 'bike', 'book',
       'music_musical_theme', 'twitter', 'product',
       'aircraft_flight_pilot', 'allergy', 'store', 'journal',
       'customer_customers', 'race', 'coffee', 'chinook', 'insurance',
       'medicine', 'university_school_college_activity', 'phone',
       'baseball_game_match', 'climbing', 'body', 'election', 'apartment',
       'soccer', 'performance', 'debate', 'wedding', 'epinions', 'riding',
       'gymnast', 'small', 'browser', 'wrestler', 'protein',
       'film_sakila_movie_cinema', 'gas', 'party', 'cre', 'company',
       'local', 'formula', 'machine', 'entrepreneur', 'perpetrator',
       'csu', 'candidate', 'county', 'inn', 'storm', 'news', 'restaurant',
       'icfp', 'loan', 'behavior', 'assets', 'railway_train_station',
       'sports', 'manufacturer_manufactory', 'hr', 'mountain', 'program',
       'e', 'hospital', 'ship', 'club', 'tracking', 'network',
       'decoration', 'document', 'solvency', 'entertainment', 'device',
       'shop', 'voter', 'swimming', 'dorm', 'workshop', 'roller', 'city',
       'scientist', 'wine', 'driving', 'architecture', 'culture'],
      dtype=object)

In [4]:
df.rename(columns={'db_id': 'class'}, inplace=True)

In [5]:
df.head()

,Unnamed: 0,class,query,query_toks,query_toks_no_value,question,question_toks,sql
0,0,department,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ..."
1,1,department,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","List the name, born state and age of the heads...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ..."
2,2,department,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","List the creation year, name and budget of eac...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ..."
3,3,department,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What are the maximum and minimum budget of the...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ..."
4,4,department,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees of the...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ..."

In [6]:
filter_df= df[["class","question"]].copy()
filter_df.head()

        class                                           question
0  department  How many heads of the departments are older th...
1  department  List the name, born state and age of the heads...
2  department  List the creation year, name and budget of eac...
3  department  What are the maximum and minimum budget of the...
4  department  What is the average number of employees of the...

In [9]:
allowed_classes = ['farm', 'student', 'bike', 'book', 'music_musical_theme']

In [10]:
final_df = filter_df[filter_df['class'].isin(allowed_classes)]

In [11]:
ff = final_df.sample(n=20, random_state=42)

In [12]:
ff.head()

                    class                                           question
4078              student  Find the last names of the students in third g...
5192  music_musical_theme       How many unique labels are there for albums?
231                  book  What is the number of distinct publication dates?
228                  book  List the writers who have written more than on...
5187  music_musical_theme  What are the names of all songs produced by th...

In [13]:
ff.to_csv("sampled_classification.csv", index=False)