In [1]:
import pandas as pd 
import json
df= pd.read_json("dataset/spider_data/train_spider.json")
df.describe()

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql
count,7000,7000,7000,7000,7000,7000,7000
unique,140,3964,3962,3886,6962,6962,3580
top,college_2,SELECT count(*) FROM Accounts,"[SELECT, count, (, *, ), FROM, Accounts]","[select, count, (, *, ), from, customers]",How many students are there?,"[How, many, students, are, there, ?]","{'from': {'table_units': [['table_unit', 0]], ..."
freq,170,6,6,13,4,4,89

In [3]:
filter_df= df[["db_id","question"]].copy()
filter_df.head()

                   db_id                                           question
0  department_management  How many heads of the departments are older th...
1  department_management  List the name, born state and age of the heads...
2  department_management  List the creation year, name and budget of eac...
3  department_management  What are the maximum and minimum budget of the...
4  department_management  What is the average number of employees of the...

In [4]:
sampled_df=filter_df.sample(n=3, random_state=43)
sampled_df.head()

             db_id                                           question
6335  e_government  What are the payment method codes that have be...
211         bike_1  What is the average latitude and longitude of ...
3582       music_1  What are the ids of all songs that are availab...

In [6]:
sampled_df.to_csv("sampled_queries.csv", index=False)