In [1]:
import pandas as pd 
import json
df= pd.read_json("D:/data_sci/benchmarking_tool/dataset/spider_data/spider_data/train_spider.json")
df.describe()

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql
count,7000,7000,7000,7000,7000,7000,7000
unique,140,3964,3962,3886,6962,6962,3580
top,college_2,SELECT count(*) FROM Accounts,"[SELECT, count, (, *, ), FROM, Accounts]","[select, count, (, *, ), from, customers]",How many students are there?,"[How, many, students, are, there, ?]","{'from': {'table_units': [['table_unit', 0]], ..."
freq,170,6,6,13,4,4,89

In [2]:
filter_df= df[["db_id","question","query"]].copy()
filter_df.head()

,db_id,question,query
0,department_management,How many heads of the departments are older th...,SELECT count(*) FROM head WHERE age > 56
1,department_management,"List the name, born state and age of the heads...","SELECT name , born_state , age FROM head ORD..."
2,department_management,"List the creation year, name and budget of eac...","SELECT creation , name , budget_in_billions ..."
3,department_management,What are the maximum and minimum budget of the...,"SELECT max(budget_in_billions) , min(budget_i..."
4,department_management,What is the average number of employees of the...,SELECT avg(num_employees) FROM department WHER...

In [3]:
sampled_df=filter_df.sample(n=12, random_state=43)
sampled_df.head()

,db_id,question,query
6335,e_government,What are the payment method codes that have be...,SELECT payment_method_code FROM parties GROUP ...
211,bike_1,What is the average latitude and longitude of ...,"SELECT avg(T1.lat) , avg(T1.long) FROM statio..."
3582,music_1,What are the ids of all songs that are availab...,"SELECT f_id FROM files WHERE formats = ""mp4""..."
1411,college_2,How many students are in each department?,"SELECT count(*) , dept_name FROM student GROU..."
5024,soccer_2,Find the names of either colleges in LA with g...,SELECT cName FROM College WHERE enr < 13000 ...

In [4]:
sampled_df.to_csv("sampled_queries_6_5_2025.csv", index=False)